# AI Assignment 2

## Q1. 8 - puzzle problem

In [3]:
import numpy as np
from collections import deque

def print_state(state):
    for row in state:
        print(row)
    print()

def get_blank_pos(state):
    return tuple(np.where(state == 0))

def get_possible_moves(state):
    moves = []
    row, col = get_blank_pos(state)
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]  # up, down, left, right
    
    for dx, dy in directions:
        new_row, new_col = row + dx, col + dy
        if 0 <= new_row < 3 and 0 <= new_col < 3:
            new_state = state.copy()
            # Swap the blank tile
            new_state[row, col] = new_state[new_row, new_col]
            new_state[new_row, new_col] = 0
            moves.append(new_state)
    
    return moves

def solve_puzzle(start, goal):
    start = np.array(start)
    goal = np.array(goal)
    visited = set()
    queue = deque([(start, [])])  # (state, moves)
    
    while queue:
        current_state, path = queue.popleft()
        current_tuple = tuple(map(tuple, current_state))
        
        if np.array_equal(current_state, goal):
            return path
            
        if current_tuple in visited:
            continue
            
        visited.add(current_tuple)
        
        for next_state in get_possible_moves(current_state):
            if tuple(map(tuple, next_state)) not in visited:
                queue.append((next_state, path + [next_state]))
                
    return None

# Test with given initial and goal states
start = [
    [1, 2, 3],
    [8, 0, 4],
    [7, 6, 5]
]

goal = [
    [2, 8, 1],
    [0, 4, 3],
    [7, 6, 5]
]

print("Initial State:")
print_state(np.array(start))

print("Goal State:")
print_state(np.array(goal))

print("Solving...")
solution = solve_puzzle(start, goal)

if solution:
    print("Solution found! Steps:")
    for i, step in enumerate(solution, 1):
        print(f"Step {i}:")
        print_state(step)
else:
    print("No solution found!")



Initial State:
[1 2 3]
[8 0 4]
[7 6 5]

Goal State:
[2 8 1]
[0 4 3]
[7 6 5]

Solving...
Solution found! Steps:
Step 1:
[1 0 3]
[8 2 4]
[7 6 5]

Step 2:
[0 1 3]
[8 2 4]
[7 6 5]

Step 3:
[8 1 3]
[0 2 4]
[7 6 5]

Step 4:
[8 1 3]
[2 0 4]
[7 6 5]

Step 5:
[8 1 3]
[2 4 0]
[7 6 5]

Step 6:
[8 1 0]
[2 4 3]
[7 6 5]

Step 7:
[8 0 1]
[2 4 3]
[7 6 5]

Step 8:
[0 8 1]
[2 4 3]
[7 6 5]

Step 9:
[2 8 1]
[0 4 3]
[7 6 5]



## Q2. Water Jug problem

#### Approach 1

In [2]:
def water_Jug():
    x = 0
    y = 0
    
    steps = []
    
    steps.append((x,y))
    
    y = 3
    steps.append((x,y))
    
    transfer = min(4 - x,y)
    x += transfer
    y -= transfer
    steps.append((x,y))
    
    y = 3
    steps.append((x,y))
    
    transfer = min(4 - x,y)
    x += transfer
    y -= transfer
    steps.append((x,y))
    
    x = 0
    steps.append((x,y))
    
    transfer = min(4 - x,y)
    x += transfer
    y -= transfer
    steps.append((x,y))
    
    for step in steps:
        print(f'Jug of 4l : {step[0]} , Jug of 3l : {step[1]}')
        
water_Jug()

Jug of 4l : 0 , Jug of 3l : 0
Jug of 4l : 0 , Jug of 3l : 3
Jug of 4l : 3 , Jug of 3l : 0
Jug of 4l : 3 , Jug of 3l : 3
Jug of 4l : 4 , Jug of 3l : 2
Jug of 4l : 0 , Jug of 3l : 2
Jug of 4l : 2 , Jug of 3l : 0


#### Approach 2

In [4]:
def water_Jug2():
    steps = []
    jug4 = 0
    jug3 = 0
    
    steps.append((jug4, jug3))
    
    jug4 = 4
    steps.append((jug4, jug3))
    
    transfer = min(jug4, 3 - jug3)
    jug4 -= transfer
    jug3 += transfer
    steps.append((jug4, jug3))
    
    jug3 = 0
    steps.append((jug4, jug3))
    
    transfer = min(jug4, 3 - jug3)
    jug4 -= transfer
    jug3 += transfer
    steps.append((jug4, jug3))
    
    jug4 = 4
    steps.append((jug4, jug3))
    
    transfer = min(jug4, 3 - jug3)
    jug4 -= transfer
    jug3 += transfer
    steps.append((jug4, jug3))
    
    jug3 = 0
    steps.append((jug4,jug3))
    
    for step in steps:
        print(f'Jug of 4l : {step[0]} , Jug of 3l : {step[1]}')
        

water_Jug2()

Jug of 4l : 0 , Jug of 3l : 0
Jug of 4l : 4 , Jug of 3l : 0
Jug of 4l : 1 , Jug of 3l : 3
Jug of 4l : 1 , Jug of 3l : 0
Jug of 4l : 0 , Jug of 3l : 1
Jug of 4l : 4 , Jug of 3l : 1
Jug of 4l : 2 , Jug of 3l : 3
Jug of 4l : 2 , Jug of 3l : 0


## Q3. Travelling Salesman problem

In [1]:
from itertools import permutations

nodes = [1,2,3,4]

dist_mat = {
    (1,2) : 10,
    (2,1) : 10,
    (1,3) : 15,
    (3,1) : 15,
    (1,4) : 20,
    (4,1) : 20,
    (2,3) : 35,
    (3,2) : 35,
    (2,4) : 25,
    (4,2) : 25,
    (3,4) : 30,
    (4,3) : 30,
}

shortest_dist = float('inf')
shortest_path = None

for perm in permutations(nodes):
    cur_dist = 0
    
    for i in range(len(perm) - 1):
        cur_dist += dist_mat[(perm[i],perm[i+1])]
        
    cur_dist += dist_mat[(perm[-1],perm[0])]
    
    if cur_dist < shortest_dist:
        shortest_dist = cur_dist
        
        shortest_path = perm
        
        
print('Shortest Path : ',shortest_path)
print('Shortest Distance : ',shortest_dist)

Shortest Path :  (1, 2, 4, 3)
Shortest Distance :  80
