# Assignment 4

### Q1.

In [2]:
import heapq

def misplaced_tiles(state, goal):
    return sum(1 for i in range(3) for j in range(3) if state[i][j] != goal[i][j] and state[i][j] != 0)

def get_neighbors(state):
    neighbors = []
    x, y = next((i, j) for i in range(3) for j in range(3) if state[i][j] == 0)  
    moves = {
        'up': (x - 1, y),
        'down': (x + 1, y),
        'left': (x, y - 1),
        'right': (x, y + 1)
    }
    for move, (nx, ny) in moves.items():
        if 0 <= nx < 3 and 0 <= ny < 3:
            new_state = [row[:] for row in state]  
            new_state[x][y], new_state[nx][ny] = new_state[nx][ny], new_state[x][y] 
            neighbors.append(new_state)
    return neighbors

def best_first_search(initial, goal):
    heap = []
    heapq.heappush(heap, (misplaced_tiles(initial, goal), initial, []))  
    visited = set()
    while heap:
        _, current, path = heapq.heappop(heap)
        if current == goal:
            print("\nSolution found in", len(path), "moves!")
            for i, step in enumerate(path + [current]):
                print(f"\nStep {i}:")
                for row in step:
                    print(row)
            return
        visited.add(tuple(map(tuple, current)))
        for neighbor in get_neighbors(current):
            if tuple(map(tuple, neighbor)) not in visited:
                heapq.heappush(heap, (misplaced_tiles(neighbor, goal), neighbor, path + [current]))

initial_state = [
    [2, 0, 3],
    [1, 8, 4],
    [7, 6, 5]
]
goal_state = [
    [1, 2, 3],
    [8, 0, 4],
    [7, 6, 5]
]
best_first_search(initial_state, goal_state)


Solution found in 3 moves!

Step 0:
[2, 0, 3]
[1, 8, 4]
[7, 6, 5]

Step 1:
[0, 2, 3]
[1, 8, 4]
[7, 6, 5]

Step 2:
[1, 2, 3]
[0, 8, 4]
[7, 6, 5]

Step 3:
[1, 2, 3]
[8, 0, 4]
[7, 6, 5]


### Q2.

In [4]:
import numpy as np

def misplaced_tiles(state, goal):
    return np.sum(state != goal) - 1

def get_possible_moves(state):
    moves = []
    row, col = np.where(state == 0)
    row, col = row[0], col[0]
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    for dr, dc in directions:
        new_row, new_col = row + dr, col + dc
        if 0 <= new_row < 3 and 0 <= new_col < 3:
            new_state = state.copy()
            new_state[row, col], new_state[new_row, new_col] = new_state[new_row, new_col], new_state[row, col]
            moves.append(new_state)
    return moves

def hill_climbing(initial, goal):
    current_state = initial.copy()
    move_count = 0
    while not np.array_equal(current_state, goal):
        print(f"Step {move_count}:")
        print(current_state, "\n")
        possible_moves = get_possible_moves(current_state)
        best_move = min(possible_moves, key=lambda x: misplaced_tiles(x, goal))
        if misplaced_tiles(best_move, goal) >= misplaced_tiles(current_state, goal):
            print("Stuck in local maxima! No better move found.")
            break
        current_state = best_move
        move_count += 1
    print("Final State:")
    print(current_state)
    print(f"Total Moves: {move_count}")

initial_state = np.array([[2, 8, 3],
                          [1, 5, 4],
                          [7, 0, 6]])
goal_state = np.array([[1, 2, 3],
                        [8, 0, 4],
                        [7, 6, 5]])
hill_climbing(initial_state, goal_state)


Step 0:
[[2 8 3]
 [1 5 4]
 [7 0 6]] 

Step 1:
[[2 8 3]
 [1 0 4]
 [7 5 6]] 

Stuck in local maxima! No better move found.
Final State:
[[2 8 3]
 [1 0 4]
 [7 5 6]]
Total Moves: 1


### Q3.

In [8]:
from heapq import heappush, heappop

def get_moves(state):
    moves = []
    row, col = [(r, c) for r in range(3) for c in range(3) if state[r][c] == 0][0]
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)] 
    for dr, dc in directions:
        new_row, new_col = row + dr, col + dc
        if 0 <= new_row < 3 and 0 <= new_col < 3:
            new_state = [row[:] for row in state]  
            new_state[row][col], new_state[new_row][new_col] = new_state[new_row][new_col], new_state[row][col]
            moves.append(new_state)
    return moves

def solve_puzzle(initial, goal):
    open_list = []
    heappush(open_list, (0, initial, [])) 
    visited = set()
    while open_list:
        _, state, path = heappop(open_list)
        print("\nStep:")
        for row in state:
            print(row)
        if state == goal:
            print("\nSolution found.")
            return
        visited.add(tuple(map(tuple, state)))
        for move in get_moves(state):
            if tuple(map(tuple, move)) not in visited:
                heappush(open_list, (len(path) + 1, move, path + [move]))
    print("No solution found.")

initial_state = [[2, 3, 0], [1, 8, 4], [7, 6, 5]]
goal_state = [[1, 2, 3], [8, 0, 4], [7, 6, 5]]
solve_puzzle(initial_state, goal_state)


Step:
[2, 3, 0]
[1, 8, 4]
[7, 6, 5]

Step:
[2, 0, 3]
[1, 8, 4]
[7, 6, 5]

Step:
[2, 3, 4]
[1, 8, 0]
[7, 6, 5]

Step:
[0, 2, 3]
[1, 8, 4]
[7, 6, 5]

Step:
[2, 3, 4]
[1, 0, 8]
[7, 6, 5]

Step:
[2, 3, 4]
[1, 8, 5]
[7, 6, 0]

Step:
[2, 8, 3]
[1, 0, 4]
[7, 6, 5]

Step:
[1, 2, 3]
[0, 8, 4]
[7, 6, 5]

Step:
[2, 0, 4]
[1, 3, 8]
[7, 6, 5]

Step:
[2, 3, 4]
[0, 1, 8]
[7, 6, 5]

Step:
[2, 3, 4]
[1, 6, 8]
[7, 0, 5]

Step:
[2, 3, 4]
[1, 8, 5]
[7, 0, 6]

Step:
[2, 8, 3]
[0, 1, 4]
[7, 6, 5]

Step:
[2, 8, 3]
[1, 4, 0]
[7, 6, 5]

Step:
[2, 8, 3]
[1, 6, 4]
[7, 0, 5]

Step:
[0, 2, 4]
[1, 3, 8]
[7, 6, 5]

Step:
[0, 3, 4]
[2, 1, 8]
[7, 6, 5]

Step:
[0, 8, 3]
[2, 1, 4]
[7, 6, 5]

Step:
[1, 2, 3]
[7, 8, 4]
[0, 6, 5]

Step:
[1, 2, 3]
[8, 0, 4]
[7, 6, 5]

Solution found.


### Q4.

In [10]:
class Node:
    def __init__(self, name, heuristic):
        self.name = name
        self.heuristic = heuristic
        self.children = [] 
    def add_child(self, child, cost):
        self.children.append((child, cost))

def ao_star(node):
    if not node.children: 
        return node.heuristic
    min_cost = float('inf')
    best_child = None
    for child, cost in node.children:
        child_cost = ao_star(child) + cost
        if child_cost < min_cost:
            min_cost = child_cost
            best_child = child
    node.heuristic = min_cost  
    return node.heuristic

G = Node('G', 5)
H = Node('H', 7)
E = Node('E', 4)
F = Node('F', 4)
B = Node('B', float('inf'))
C = Node('C', 12)
D = Node('D', float('inf'))
A = Node('A', float('inf'))

B.add_child(G, 1)
B.add_child(H, 1)
D.add_child(E, 1)
D.add_child(F, 1)

A.add_child(B, 6)
A.add_child(C, 12)
A.add_child(D, 10)

optimal_cost = ao_star(A)
print("Optimal Cost from A:", optimal_cost)

Optimal Cost from A: 12
